//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DryFood.Areas.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTDONHANG
    {
        public int MaDH { get; set; }
        public int MaSP { get; set; }
        public int SoLuong { get; set; }
        public Nullable<decimal> GiaMua { get; set; }
        public Nullable<decimal> TongTienSP { get; set; }
    
        public virtual DONHANG DONHANG { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
