//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DryFood.Areas.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DONHANG()
        {
            this.CTDONHANG = new HashSet<CTDONHANG>();
        }
    
        public int MaDH { get; set; }
        public string NoiGiao { get; set; }
        public System.DateTime NgayDat { get; set; }
        public string NhanXet { get; set; }
        public int MaKH { get; set; }
        public Nullable<int> MaKM { get; set; }
        public Nullable<int> MaPTTT { get; set; }
        public Nullable<decimal> TamTinh { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
        public int MaTrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDONHANG> CTDONHANG { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual KHUYENMAI KHUYENMAI { get; set; }
        public virtual PTTT PTTT { get; set; }
    }
}
