//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DryFood.Areas.Admin.Data
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity.Infrastructure;

    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CTDONHANG = new HashSet<CTDONHANG>();
        }
    
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public string MoTa { get; set; }
        public int SoLuong { get; set; }
        public decimal GiaBan { get; set; }
        public string AnhSP { get; set; }
        public System.DateTime NgayNhap { get; set; }
        public int SoLanBan { get; set; }
        public int TrangThaiSP { get; set; }
        public int MaLoai { get; set; }
        public int MaNCC { get; set; }

        internal static DbQuery<SANPHAM> Where(Func<object, bool> p)
        {
            throw new NotImplementedException();
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDONHANG> CTDONHANG { get; set; }
        public virtual LOAI LOAI { get; set; }
        public virtual NHACUNGUNG NHACUNGUNG { get; set; }
    }
}
