//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DryFood.Areas.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAIKHOAN
    {
        public int MaKH { get; set; }
        public string MatKhau { get; set; }
        public string SDT { get; set; }
        public Nullable<int> DiemTichLuy { get; set; }
        public string Roles { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
